### ISSUE TITLE
1.2.1 Not Working on FireTV (Android)

### ISSUE THREAD

**Issue by ticollins91** [notspiff/visualization.shadertoy#50] opened 2019-10-02 20:52 UTC
Hi,

Just installed the latest update 1.2.1 on all my Kodi devices (1 x Windows, 2 X FireTV 3rd Gen). All devices are running the latest stable version of Kodi 18.4.

The windows release of shadertoy works fine however the FireTVs don't work. The visualization starts but then there is no movement to the visualization.

**Comment by AlwinEsch** [comment] 2019-10-02 20:57
Have you a way to get the kodi.log (as Debug) from FireTV, that I can see the used GLES Version there to reproduce fault?

**Comment by ticollins91** [comment] 2019-10-02 21:38
Sure, I can't get hold of it right now but will upload it tomorrow.

**Comment by AlwinEsch** [comment] 2019-10-03 07:46
Have checked on my two available Android system, there it has worked.

Also to be sure to have understood it correctly, with **there is no movement to the visualization** do you mean the screen stays black?

Was it not working on all available Presets or only on few of them?
If only few then maybe becomes fixed with this: https://github.com/xbmc/visualization.shadertoy/pull/49 on "add textureLod fallback on GLES (needed on some shadertoys)"
and you can try with the ZIP's from there https://jenkins.kodi.tv/job/xbmc/job/visualization.shadertoy/job/PR-49/2/

EDIT:
During test found only Preset **"Beating Circles by Phoenix72"** where visible but no movement.

**Comment by ticollins91** [comment] 2019-10-03 20:24
The default one i normally use is visible but no movement and I havnen't found any that work with the new update. See example here: [https://imgur.com/XDoLF9Y](https://imgur.com/XDoLF9Y)

Kodi debug log here: [https://paste.kodi.tv/dazawoxeli.kodi](https://paste.kodi.tv/dazawoxeli.kodi)

**Comment by ticollins91** [comment] 2019-10-03 20:31
After some more testing I have found that the majority of them are visible with no movement, some don't show anything, a few seriously slow down my unit to approx 5fps and then i struggle to change it to a different one. I have found 4 that work:

AudioVisual
BPM
Dancing Metalights
Twisted Rings

Edit: this is with verison 1.2.2 you linked to

**Comment by AlwinEsch** [comment] 2019-10-04 03:19
Have changed the performace check a bit with https://github.com/xbmc/visualization.shadertoy/pull/49/commits/9097388b537f5311c758de77009860bbb1108bfe 
It has also improved a little on my Linux, since it then adjusts the processed resolution immediately.

Can you try again with here https://jenkins.kodi.tv/job/xbmc/job/visualization.shadertoy/job/PR-49/5/

**Comment by ticollins91** [comment] 2019-10-04 21:12
No improvement with that version.

**Comment by AlwinEsch** [comment] 2019-10-04 21:18
Shit :cold_sweat: :disappointed:, I go tomorrow in the Market to buy one :smile:
Is that comparable to yours https://www.mediamarkt.de/de/product/_amazon-fire-tv-stick-4k-mit-der-neuen-alexa-sprachfernbedienung-2490802.html ?

EDIT: Maybe both available types: https://www.mediamarkt.de/de/product/_amazon-fire-tv-stick-mit-der-neuen-alexa-sprachfernbedienung-2-generation-2516061.html
Are not so expensive :wink:

**Comment by ticollins91** [comment] 2019-10-04 21:30
No, it's the 3rd gen Fire TV (not the stick)

like this: https://ebay.us/hEQT4O

Although don't go buying a device just for my benefit! Can I provide any more logs that could help?

**Comment by AlwinEsch** [comment] 2019-10-05 22:34
Not only for here :smile:, it's also better for other stuff to have for testing.

Got it to me and think to see what you mean.
Circuits by Kali, freeze Kodi complete. Some others are calculated to very low resolution and stutter. 

Looked the CPU usage in normal values, will try to execute the Shadertoy parts elsewhere (Browser), to see if the OS does not bring anything better or hangs on even Kodi.

**Comment by ticollins91** [comment] 2019-10-06 10:31
Thanks for looking into it!

Let me know when there is a new version to test and can give you new logs if needed.

**Comment by Psychoses** [comment] 2019-10-06 20:14
Hello,
@tmortonorr @AlwinEsch

same problem here. after 1.2.1 update.
windows : all is good.
android device : It's like the visualizer can't detect sound. The bar exist but don't move. like @tmortonorr.
i think visualisation work but have just no sound "data/info" for move bar, etc...
my android device is a "android-armv7" "Xiaomi Mi Box 3 (MDZ-16A-AB)"

I will back if i found anything. Thanks.

edit:
1.1.10 : ok
1.2.0 : same bug
1.2.2 (PR-49/5) : same bug
my device like the FireTV use Mali-450. I don't know if that can help.
same problem appear on my smartphone "xiaomi mido" "aarch64" "Snapdragon625/Adreno506"

**Comment by AlwinEsch** [comment] 2019-10-08 16:05
Have checked with Firefox on Fire TV Stick (it was Frozzen like Kodi :joy:), there the same. The performance not good enough.
I look now to prevent not working shaders or to bring back as it was on 1.1.10 (https://github.com/xbmc/visualization.shadertoy/blob/1.1.10-Leia/src/main.cpp#L64-L89)

Have used for check of 1.2.0 and above a 64bit ARM on my Mobile phone and Raspberry 3. As a result, it was not there and ran normally.

**Comment by AlwinEsch** [comment] 2019-12-16 14:50
The bad ones are now prevent again like before

**Closed as completed by AlwinEsch** 2019-12-16 14:50 UTC
